name: Daily Deployment

on:
#  schedule:
#    - cron: 0 12 * * *  # 日本時間20:00に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install --frozen-lockfile
    - run: yarn run test

    - name: Fetch & build data
      run: |
        rm data/data.json
        rm data/news.json
        rm data/municipalities-data.json
        curl -L https://stopcovid19.code4nara.org/api/data.json -o data/data.json
        curl -L https://stopcovid19.code4nara.org/api/news.json -o data/news.json
        curl -L https://stopcovid19.code4nara.org/api/municipalities-data.json -o data/municipalities-data.json

    - name: Upload json data
      uses: actions/upload-artifact@v1
      with:
        name: data
        path: data

    - run: yarn run generate:deploy --fail-on-page-error

#   - name: deploy
#     uses: peaceiris/actions-gh-pages@v3
#     with:
#       github_token: ${{ secrets.GITHUB_TOKEN }}
#       publish_dir: ./dist
#       publish_branch: production
