# deploymentイベントをトリガーに実行されるGitHub Actionsジョブ
name: deployment

on:
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Update deploy status to in_progress
        uses: rsotnychenko/deployment-status-update@0.1.3
        with:
          status: "in_progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test

      - name: Fetch & build data
        run: |
          # 奈良市データを所定のサーバーから取得 (TODO: newsが上記処理と重複しているのを直す)
          rm data/data.json
          rm data/news.json
          rm data/data_naracity.json
          curl -L https://stopcovid19.code4nara.org/api/data.json -o data/data.json
          curl -L https://stopcovid19.code4nara.org/api/news.json -o data/news.json
          curl -L https://stopcovid19.code4nara.org/api/data_naracity.json -o data/data_naracity.json

      - run: yarn run generate:deploy --fail-on-page-error

      - name: set robots.txt
        if: github.event.deployment.ref == 'development'
        run: "echo \"User-agent: *\nDisallow *\" > ./dist/robots.txt"

      - name: deploy for development
        if: github.event.deployment.ref == 'development'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dev-pages

      #- name: rsync deploy for development
      #  if: github.event.deployment.ref == 'development'
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    rsync -auzrv -e "ssh -i ~/.ssh/id_25519_github -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 65522" ./data/* ishizuka@stopcovid19.code4nara.org:/home/ishizuka/test/

      - name: deploy for production
        if: github.event.deployment.ref == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: production

      - name: Update deploy status to success|failure|cancelled
        if: always()
        uses: rsotnychenko/deployment-status-update@0.1.3
        with:
          status: ${{ job.status }}
          auto_inactive: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
