name: staging deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test

      - name: Fetch & build data
        run: |
          rm data/data.json
          rm data/news.json
          rm data/municipalities-data.json
          curl -L https://stopcovid19.code4nara.org/api/data.json -o data/data.json
          curl -L https://stopcovid19.code4nara.org/api/news.json -o data/news.json
          curl -L https://stopcovid19.code4nara.org/api/municipalities-data.json -o data/municipalities-data.json

      - run: yarn run generate:deploy --fail-on-page-error
      - run: "echo \"User-agent: *\nDisallow *\" > ./dist/robots.txt"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      #- name: Rsync Deploy
      #  run: |
      #    echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      #    rsync -rptgDvz --delete -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 65522" dist/* covid19@stopcovid19.code4nara.org:/usr/share/nginx/covid19-staging/	  
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
